# -*- coding: utf-8 -*-
"""COGNIFYZ Task 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ha45EpK-hTkPQdqGFK2rvRLWdGb0-zm6

#Task 1:- Data Overview

Objective: Understand the dataset structure.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as exp
import statsmodels.formula.api as smf

data=pd.read_excel("/content/COGNIFYZ.xlsx")
data

data.head()

data.shape

"""Interpretation:-

The dataset has 40 rows and 24 columns.

There are 40 entries or observations in the dataset, and each observation has 24 attributes or features.
"""

data.info()

"""Interpretation:-

The data types include integers (int64), objects (object, typically representing strings), and categorical variables such as gender, investment avenues, etc.
"""

data.columns

"""The data.columns gives us the Information about the total number of columns and their Names."""

data.isnull().sum()

"""From the above result , we get to know that there are no null values included in the datset. Hence can proceed with Further Statistical Analysis.

"""

print(data.describe())

"""Interpretations:-
The Descriptive Statistics is given above.The descriptive statistics include Total Count , Mean, Standard Deviation , Minimum, Maximum and the Quantiles (25%,50%,75%).
"""